### PR TITLE
Add column widths checking and refactor code

### PR DESCRIPTION
**Pull request by djhoese**
So this is kind of what I was thinking for #1. I got kind of out of control and refactored a ton of the code, but am seeing some major improvements on my machine. I screwed something up and the second row (the one with the `-`) doesn't seem to be the right length.

However, the main feature here as far as performance comes if you set `column_widths=True`. This only uses the first row of data to determine the column widths and keeps the table as a generator. I also changed the alpha determining code to always only use the first row. I didn't see a reason for it to use every row if we assume column types are consistent.

Working on fixing the output...let me know what you think otherwise. Sorry this only made it in one commit.

### CODE REVIEW

**Comment by djhoese** [comment]
I had used `zip` for the output parts that use `key_lengths` and `headers` but didn't see a meaningful increase in performance even though the code felt cleaner.

Note, I updated the docstring formatting to be PEP8.

Feel free to use any parts of what I did or none of them. I don't really need to use this code in my every day work, but thought it was a cool project. Nice job.

**Comment by divi255** [comment]
I've moved a little far away in format_table so I'm afraid it will not merge automatically. but I'll reset the branch, test it and merge new features somehow if they don't slow it down

except about alpha - I have many tables with mixed col values, we can make number detection in a first row only as an option e.g. homogeneous_input=True

about tuples vs lists: that's actually strange behavior, if you make 2 test functions and test list.append and tuple += tuple, the speed is equal. but in format_table switching to lists slows it down on 2/3%,  maybe my test server is joking on me or I miss something

**Comment by djhoese** [comment]
Another thing I was looking at, in your pandas benchmark tests you create the DataFrame and do a couple operations to it before printing out. Is that a fair comparison?

**Comment by divi255** [comment]
so, I've implemented different align methods, including ALIGN_HOMOGENEOUS_NUMBERS_RIGHT as you recommended and yes - it works slightly faster on a large tables, thanks! But I made it a little different way - it uses first row where checked column is not None.

zip in headers formatting - if we use zip, then we don't need lkr range at all, I've included it as:

for i, (ht, key_len) in enumerate(zip(headers if headers else keys, key_lengths)):

the next is to implement column width, your argument seems to be fine, except again - I would rather set column width from the first row where column value is not None. Agree?

**Pull request closed without merging**
